# Customer Churn Model Deployment

## Objective

The objective of this notebook is to demonstrate how the trained CatBoost model can be used to predict customer churn for new customer records.

The notebook covers:

- Loading the trained model
- Making predictions
- Predicting churn probability
- Batch inference
- Saving prediction results

This notebook simulates the inference stage of a production machine learning system.

In [1]:
import joblib
import pandas as pd

In [2]:
model = joblib.load("../models/catboost_pipeline.pkl")

print("Model loaded successfully!")

Model loaded successfully!

In [4]:
df = pd.read_csv("../data/processed/telco_feature_engineered.csv")

X = df.drop(
    columns=[
        "customerID",
        "Churn",
        "Churn_Binary"
    ]
)

y = df["Churn_Binary"]

In [5]:
customer = X.iloc[[0]]

prediction = model.predict(customer)

probability = model.predict_proba(customer)

print("Prediction :", prediction)

print("Probability :", probability)

Prediction : [1]
Probability : [[0.34977537 0.65022463]]

In [6]:
sample = X.iloc[:10]

predictions = model.predict(sample)

probabilities = model.predict_proba(sample)

results = sample.copy()

results["Prediction"] = predictions

results["Stay Probability"] = probabilities[:,0]

results["Churn Probability"] = probabilities[:,1]

results.head(10)

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,MonthlyCharges,TotalCharges,AvgMonthlySpend,TotalServices,HasFamily,TenureGroup,SpendingGroup,Prediction,Stay Probability,Churn Probability
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,29.85,29.85,29.850000,1,0,New,Low,1,0.349775,0.650225
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,56.95,1889.50,55.573529,3,0,Established,Medium,0,0.948087,0.051913
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,53.85,108.15,54.075000,3,0,New,Medium,0,0.636286,0.363714
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,42.30,1840.75,40.905556,3,0,Established,Low,0,0.954331,0.045669
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,70.70,151.65,75.825000,1,0,New,Medium,1,0.336492,0.663508
5,Female,0,No,No,8,Yes,Yes,Fiber optic,No,No,...,99.65,820.50,102.562500,5,0,New,High,1,0.189580,0.810420
6,Male,0,No,Yes,22,Yes,Yes,Fiber optic,No,Yes,...,89.10,1949.40,88.609091,4,0,Growing,High,0,0.576159,0.423841
7,Female,0,No,No,10,No,No phone service,DSL,Yes,No,...,29.75,301.90,30.190000,1,0,New,Low,0,0.743329,0.256671
8,Female,0,Yes,No,28,Yes,Yes,Fiber optic,No,No,...,104.80,3046.05,108.787500,6,0,Established,High,1,0.460647,0.539353
9,Male,0,No,Yes,62,Yes,No,DSL,Yes,Yes,...,56.15,3487.95,56.257258,3,0,Loyal,Medium,0,0.970173,0.029827

In [7]:
pred = model.predict(X)

prob = model.predict_proba(X)

deployment_results = X.copy()

deployment_results["Prediction"] = pred

deployment_results["Stay Probability"] = prob[:,0]

deployment_results["Churn Probability"] = prob[:,1]

deployment_results.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,MonthlyCharges,TotalCharges,AvgMonthlySpend,TotalServices,HasFamily,TenureGroup,SpendingGroup,Prediction,Stay Probability,Churn Probability
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,29.85,29.85,29.850000,1,0,New,Low,1,0.349775,0.650225
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,56.95,1889.50,55.573529,3,0,Established,Medium,0,0.948087,0.051913
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,53.85,108.15,54.075000,3,0,New,Medium,0,0.636286,0.363714
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,42.30,1840.75,40.905556,3,0,Established,Low,0,0.954331,0.045669
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,70.70,151.65,75.825000,1,0,New,Medium,1,0.336492,0.663508

In [8]:
deployment_results.to_csv(
    "../reports/churn_predictions.csv",
    index=False
)

print("Predictions saved successfully!")

Predictions saved successfully!

# Business Interpretation

The deployed model can be integrated into customer relationship management (CRM) systems to estimate the likelihood of customer churn for each customer.

Customers with higher churn probabilities can be targeted with personalized retention strategies, such as discounts, loyalty rewards, or proactive customer support.

This allows businesses to prioritize high-risk customers and improve customer retention while reducing revenue loss.

# Conclusion

The trained CatBoost model was successfully deployed for inference.

The deployment workflow includes:

- Loading the trained model
- Predicting churn
- Estimating churn probabilities
- Performing batch predictions
- Exporting prediction results

This notebook demonstrates how a trained machine learning model can be integrated into real-world business applications.

The Customer Churn Prediction project is now complete, covering the full machine learning lifecycle from business understanding to deployment.